### ISSUE TITLE
Crear en el DSL soporte para añadir un buscador local web sobre los resultados

### ISSUE THREAD

**Issue by fjlopez** [Shathe/101CrawlersWeb#26]
Esto permite instalar en la imagen una herramienta para poder buscar sobre los resultados. Analizar si se puede configurar que durante la ejecución del crawler se produzca una indexación incremental de los dump, al final de la ejecución o bajo demanda.

**Comment by Shathe** [comment]
No se ha realizado del todo lo especificado por decisión de diseño.
En el DSL se especifica solo si se quiere indexar en cada ronda o solo al terminar.
Que se realize bajo demanda se deja al libre uso, tanto por simplificar el desarrollo, como debido a que alguien puede querer solo indexar al final, pero tener la posibilidad de poder indexar tambien cuando quiera.

Ahora se indexa según lo especifiado en el DSL, y bajo demanda cuando se quiera.
Las indexaciones están centralizadas en el sistema. 
Cuando alguien indexa bajo demanda se indexa en el sistema.
Cuando se indexa según lo dicho en el DSL, se indexa en el Docker, pero, cuando se realize una consulta, si el índice del contenedor docker está más actualizado que el del sistema, se copiará el indice


Se ha comprobado que el sistema que está actualemnte con los cambios de este issue funcione perfectamente.
Se ha buscado la mejor solución posible.
cdd2e7af42eb3e7d0d5734ef99d9aca2bc918fdf
Se corrigieron bugs respecto a ese commit
