### ISSUE TITLE
Extraer datos fuera de la contenedor

### ISSUE THREAD

**Issue by fjlopez** [Shathe/101CrawlersWeb#28]
Elaborar una estrategia para extraer los datos del contenedor.

**Comment by Shathe** [comment]
La paginación la he intentado hacer pero parece ser que el System.in entra en conflicto con la consola o algo parecido, porque llevo un rato buscando solución al problema que se meha planteado y no he encontrado el porqué ni solución.
El problema es que iba con retraso el System.in. Es decir, si por ejemplo hacias un readNextLine(), tenias que introducir dos lineas para que te respondiese (solo la primera vez) y luego ya iba con una interacción de retraso.

La solución que he encontrado y que me parece buena es esta 
850d97cee6312e4f229e1c217daa9a46d626c544
Lo que he hecho ha sido pedir el máximo de resultados que se quieren ver por pantalla. Por defecto se ven todos si no se introduce el argumento max.
También se guarda un fichero con la última busqueda que se ha realizado.

**Comment by Shathe** [comment]
Se puede ver en el paso 6 del [tutorial] (https://github.com/Shathe/101CrawlersWeb/wiki/Tutorial-%5BEN%5D)
