### ISSUE TITLE
Diagrama de arquitectura

### ISSUE THREAD

**Issue by Shathe** [Shathe/101CrawlersWeb#44]
**Una vez se integre Spring remote shell** realizar un diagrama de arquitectura basándose en [este primer acercamiento] (https://github.com/Shathe/101CrawlersWeb/blob/master/docs/(primer%20arcercamiento)%20System_Arquitecture.jpg) y así también integrar hdfs en el diagrama 

Pregutnar a Javier sobre cómo veía ese primer acercamiento. Feedback

**Comment by Shathe** [comment]
Usar Umlet

**Comment by fjlopez** [comment]
Puedes ir copiando aquí los diagramas mediante drag&drop si no me confundo.

**Comment by Shathe** [comment]
Cierro debido a #50
