### ISSUE TITLE
Creación Base de datos para el sistema web

### ISSUE THREAD

**Issue by Shathe** [Shathe/101CrawlersWeb#49]
Buscar que tipo de base de datos con persistencia donde almacenar los datos que el sistema vaya generando encaja mejor para esta primera version y crearl

**Comment by Shathe** [comment]
Como al final he decidido usar Spring, para esta versión sin tener en cuenta la parte de un File system, voy a utilizar para los primeros datos una base de datos sql (no persistente por el momento). [Aquí] (https://docs.spring.io/spring/docs/current/spring-framework-reference/html/jdbc.html) una miniguía.

**Comment by fjlopez** [comment]
JDBC Template es una buena solución inicial.

**Comment by Shathe** [comment]
Creación realizada, eso sí, de momento es dinámica, en cada ejecución se crea desde cero.
