### ISSUE TITLE
Evaluar Diagramas

### ISSUE THREAD

**Issue by Shathe** [Shathe/101CrawlersWeb#50]
[Diagramas butler] (https://github.com/Shathe/101CrawlersWeb/tree/master/docs/butler)
[Diagramas Site] (https://github.com/Shathe/101CrawlersWeb/tree/master/docs/site)

Revisar los diagramas y dar una opinón sobre ellos para poder mejorarlos o introducir más detalles

**Comment by jorcox** [comment]
El segundo enlace no funciona.

**Comment by Shathe** [comment]
Corregido, gracaispor la apreciación, ha sido un cambio de nombre

**Comment by fjlopez** [comment]
Revisados los diagramas.

**Comment by Shathe** [comment]
ServicesDiagram

no hace falta que pongas el componente Exceptions Management
“Data Base” —> “Database"
“JDBC jdbcTemplate” —> “jdbcTemplate"
puedes usar el esteriotipo <<Controller>>
y despuest DockerController, ProjectController, ...


SiteDiagram:

página 61 libro web
en esta parte del capítulo explican los componentes de una aplicación web moderna y escalable
ves que lo dividen en front end, web services, data store, ...
en tu caso si veo SiteDiagram
FileSystem y JDBC Datastore serian dos subsistemas tipo Main Data Store
Docker lo podemos ver como sistemas externos
butler, dado que es un componente podría verse de esa forma también

el servicio web sería  el que está en Web Service
faltaría el Front End
el servicio web sería  el que está en Web Service

Sería todo lo que genera el HTML y el código JS que se ejecuta en el cliente
lee el libro, es muy interesante
voy a mirar otro diagrama
ahora mismo como es todo REST lo unico que tnego en el frontend es codigo angular que controlar en one-page la aplicacion y peticiones

BuilderComponentDiagram, quizás se explica mejor con  un diagrama de actividad
El fichero YAML no es un componente, es un artefacto que es leido
Habría que dejar claro que hay plantillas de entrada y resultados de salida


ButlerDiagram

Corrige “Commadns” —> “Commands"
Si todos los componentes de Butler actúan con FileSystem coloca una línea solo entre Butler y FileSystem
Si Commands es el controlador colócalo en una fila por encima de los otros 3
Otra cosa más,
por facilidad de comprensión
imagina que la interacción con el sistema va de arriba a abajo, de izquierda a derecha
eso hace que butler vaya arriba del todo
y docker y filesystem abajo
