### ISSUE TITLE
El método Operations.readPlugins tiene bugs potenciales

### ISSUE THREAD

**Issue by fjlopez** [Shathe/101CrawlersWeb#56]
Son dos:
- Los parámetros `route` y `config` nunca son utilizados. 
- El uso de File.listFiles() puede devolver `null` si File no apunta a un directorio. Este se da dos veces en el método.

**Comment by Shathe** [comment]
fallo bastante gordo por mi parte, corregido 597dbbe892645a8805bc4cc17e6e339f42531ea1
