### ISSUE TITLE
Más diagramas, documentación del proyecto

### ISSUE THREAD

**Issue by Shathe** [Shathe/101CrawlersWeb#67]

**Comment by fjlopez** [comment]
Añade algo de descripción a esta issue para que no se te olvide qué querías contar cuando creaste la issue.

**Comment by Shathe** [comment]
Ah, no, era simplemente recordatorio, no era nada en concreto, era para pensar exactamente cuando termine la memoria qué poner en los anexos, en documentar y actualizar todas las wikis o aumentarlas es decir, es un recordatorio simplemente de que tengo que repasar toda la documentado en general
