### ISSUE TITLE
Avance memoria

### ISSUE THREAD

**Issue by Shathe** [Shathe/101CrawlersWeb#68]
- [x] Portada
- [x] Resumen
- [x] Declaración autoría
- [x] Agradecimientos
- [x] Tabla de contenido (automática)
- [x] Introducción (4 páginas)
- [x] Sistema 8-10 páginas
- [x] Tecnologías usadas 4 páginas
- [x] Evolución del sistema 2-3 páginas
- [x] Validación y pruebas 1-2 páginas
- [x] Resultados 1-2 páginas
- [x] Conclusiones 1-2 páginas
- [x] Anexos 15-30 Páginas
- [ ] Presentación por decidir y documentarme

**Comment by fjlopez** [comment]
Buena idea usar checkbox 👍

**Comment by jorcox** [comment]
Mejor que la mía de abrir 100.000 issues xD
