### ISSUE TITLE
Evaluar memoria

### ISSUE THREAD

**Issue by Shathe** [Shathe/101CrawlersWeb#70]
Evaluar la memoria del TFG

Ver si sobra algo (puntos, párrafos, imágenes, explicaciones...)
Ver si falta algo (puntos, cosas que explicar, diagramas de algún tipo, explicar algo..)
Ver si algo es mejor modificar tal como está ahora mismo.

**Comment by jorcox** [comment]
Sobran toneladas de comas.

**Comment by Shathe** [comment]
[aquí] (https://github.com/Shathe/101CrawlersWeb/blob/master/docs/Memoria%20TFG_v01.pdf)el enlace a la memoria

**Comment by fjlopez** [comment]
Acabo de hacer una primera revisión. Subida a GitHub.

**Comment by Shathe** [comment]
https://classroom.udacity.com/courses/ud730/lessons/6370362152/concepts/63798118290923
https://classroom.udacity.com/courses/ud730/lessons/6370362152/concepts/63798118290923

**Comment by Shathe** [comment]
46a86c8671bdc1f43f26cdad4099868400cfd787
46a86c8671bdc1f43f26cdad4099868400cfd787
